<div class="wrap">
    <h2>External item banners widget options</h2>

    <h3>NonStopShop insert article</h3>

    <form action="" method="post" class="external-item-banners-widget-Form" id="externalItemBannersWidgetForm">
        <label for="itemId">Article ID (required): </label>
        <input id="itemId" name="itemId" type="text" value="" class="regular-text" required/>

        <label for="title">Article title (required): </label>
        <input id="title" name="title" type="text" value="" class="regular-text " required/>

        <label for="description">Article description (required): </label>
        <textarea id="description" name="description" type="text" value="" class="regular-text" rows="5" required></textarea>

        <label for="salePrice">Article sale price:</label>
        <input id="salePrice" name="salePrice" type="text" value="" class="regular-text"/>

        <label for="regularPrice">Article regular price (required):</label>
        <input id="regularPrice" name="regularPrice" type="text" value="" class="regular-text" required/>

        <label for="categoryUrl">Article category URL (required):</label>
        <input id="categoryUrl" name="categoryUrl" type="text" value="" class="regular-text" required/>

        <!--                <label for="itemUrl">Article URL (required):</label>-->
        <!--                <input id="itemUrl" name="itemUrl" type="text" value="" class="regular-text" required/>-->

        <input type="submit" name="articleCreate" class="button button-primary" value="Create">
        <input type="submit" name="articleUpdate" class="button button-primary" value="Update">
    </form>


</div>