<div class="wrap">
    <a href="admin.php?page=external_item_banners_widget&action=form"><button class="button">Dodaj novi proizvod</button></a>
    <a href="admin.php?page=external_item_banners_widget&action=preview"><button class="button">Pregledaj carousel</button></a>

    <h3>Product list</h3>
    <table class="widefat" cellspacing="0">
        <th>Kataloski broj</th>
        <th>Slika</th>
        <th>Naslov</th>
        <th>Opis</th>
        <th>Aktivna cena</th>
        <th>Stara cena</th>
        <th>URL kategorije</th>
        <th>URL proizvoda</th>
        <th>Akcije</th>

        <?php foreach ($data as $item): ?>
            <tr>
                <td><?= $item->sku ?></td>
                <td><img src="<?= $item->image ?>" width="200" /></td>
                <td><?= $item->title ?></td>
                <td><?= $item->description ?></td>
                <td><?= $item->salePrice ?></td>
                <td><?= $item->regularPrice ?></td>
                <td><?= $item->categoryUrl ?></td>
                <td><?= $item->itemUrl ?></td>

                <td>
                    <a href="admin.php?page=external_item_banners_widget&action=form&itemId=<?=$item->itemId?>" class="button button-secondary" value="Izmeni">Izmeni</a>
                    <a href="admin.php?page=external_item_banners_widget&action=delete&itemId=<?=$item->itemId?>" class="button button-secondary" value="Obrisi">Obrisi</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>
