<div class="wrap">
    <?php if (!$product): ?>
    <h3>Dodaj novi proizvod u carousel widget</h3>
    <?php else : ?>
    <h3>Izmeni proizvod: <?=$product->title?></h3>
    <?php endif; ?>

    <table>
        <tr>
            <td>
                <form action="" method="post" class="external-item-banners-widget-Form" id="externalItemBannersWidgetForm">
                    <label for="sku">SKU : </label>
                    <input id="sku" name="sku" type="text" class="regular-text skuSearch" required value="<?php
                    if ($product) { echo $product->sku; }
                    ?>" />

                    <label for="title">Naslov: </label>
                    <input id="title" name="title" type="text" class="regular-text " required value="<?php
                    if ($product) { echo $product->title; }
                    ?>" />

                    <label for="description">Opis: </label>
                    <textarea id="description" name="description" type="text" value="" class="regular-text" rows="5" required><?php
                    if ($product) { echo $product->description; }
                    ?></textarea>

                    <label for="salePrice">Cena: </label>
                    <input id="salePrice" name="salePrice" type="text" class="regular-text" required value="<?php
                    if ($product) { echo $product->salePrice; }
                    ?>" />

                    <label for="regularPrice">Stara cena: </label>
                    <input id="regularPrice" name="regularPrice" type="text" class="regular-text" value="<?php
                    if ($product) { echo $product->regularPrice; }
                    ?>" />

                    <label for="categoryUrl">URL kategorije: </label>
                    <input id="categoryUrl" name="categoryUrl" type="text" class="regular-text" required value="<?php
                    if ($product) { echo $product->categoryUrl; }
                    ?>" />

                    <input id="imageSrc" name="imageSrc" type="hidden" class="regular-text" value="<?php
                    if ($product) { echo $product->imageSrc; }
                    ?>" />
                    <input id="image" name="image" type="hidden" class="regular-text" value="<?php
                    if ($product) { echo $product->image; }
                    ?>" />
                    <input id="itemUrl" name="itemUrl" type="hidden" class="regular-text" value="<?php
                    if ($product) { echo $product->itemUrl; }
                    ?>" />
                    <input id="itemId" name="itemId" type="hidden" class="regular-text" value="<?php
                    if ($product) { echo $product->itemId; }
                    ?>" />

                    <?php if (!$product): ?>
                        <input type="submit" name="articleCreate" class="button button-primary" value="Kreiraj" />
                    <?php else : ?>
                        <input type="submit" name="articleUpdate" class="button button-primary" value="Izmeni" />
                    <?php endif; ?>

                </form>
            </td>
            <td>
                <?php if ($product): ?>
                <img src="<?=$product->image?>" width="500" class="externalCarouselItemImage" />
                <?php else: ?>
                <img src="" width="500" class="externalCarouselItemImage" />
                <?php endif; ?>
            </td>
        </tr>
    </table>

</div>