<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta content="charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="flexslider.css?1" type="text/css" media="screen"/>
</head>
<body class="loading">

<?php if ($template === 'vertical'): ?>
    <div id="container" class="cf">
        <div id="main" role="main">
            <section class="slider">
                <div class="flexslider vertical">
                    <div class="master-title">
                        <a target="_blank" href="https://www.nonstopshop.rs">Nonstopshop.rs</a>
                    </div>
                    <ul class="slides">
                        <?php foreach ($data as $key => $item): var_dump($item); die(); ?>
                            <?php $url = str_replace('nssWidget', $ref, $item->url); ?>
                            <?php if ($key > 7) { continue; } ?>
                            <?php $k = $key + 1; ?>
                            <li data-thumb="<?=$item->image?>">
                                <a target="_blank" href="<?=$url . $k?>" title="<?=$item->title?>"><img src="<?=str_replace('small/', '', $item->image)?>" alt="<?=$item->title?>" /></a>
                                <a target="_blank"  href="<?=$url . $k?>" title="<?=$item->title?>"><h2 class="flex-caption-title" style="text-align:center;"><?=$item->title?></h2></a>
                                <!--<p class="flex-caption">Ovaj proizvod radi po prostom principu emitovanja ultrazvucnih talasa-->
                                <!--koji su veoma neprijatni za...</p>-->
                                <span class="caption-old-price"><?=$item->oldPrice?>din</span>
                                <span class="caption-new-price"><?=$item->price?>din</span>
                                <span class="caption-savings">Ušteda: <?=$item->savingsDinars?>din (<?=$item->savingsPercentage?>%)</span>
                                <a target="_blank" href="<?=$url . $k?>" class="caption-others">Pogledajte slične proizvode</a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
                <div class="master-footer">
                    <a class="master-footer-title" target="_blank" href="https://www.nonstopshop.rs/cms/sale.php">
                        Pogledajte TOP 100 proizvoda na akciji ovde
                    </a>
                </div>
            </section>
        </div>
    </div>
<?php else: ?>
    <div class="container-horizontal">
        <div class="flexslider horizontal carousel">
            <div class="master-title">
                <a target="_blank" href="https://www.nonstopshop.rs">Nonstopshop.rs</a>
            </div>
            <ul class="slides">
                <?php foreach ($data as $key => $item): ?>
                    <?php $url = str_replace('nssWidget', $ref, $item->url); ?>
                    <?php if ($key > 7) { continue; } ?>
                    <?php $k = $key + 1; ?>
                    <li>
                        <a target="_blank"  href="<?=$url . $k?>" title="<?=$item->title?>">
                            <img src="<?=str_replace('small/', '', $item->image)?>" alt="<?=$item->title?>" width="200" height="150" />
                        </a>
                        <div class="flex-caption">
                            <a target="_blank"  href="<?=$url . $k?>" title="<?=$item->title?>">
                                <h3 class="flex-caption-title" style="text-align:center;"><?=$item->title?></h3>
                            </a>
                            <span class="caption-old-price"><?=$item->oldPrice?>din</span>
                            <span class="caption-new-price"><?=$item->price?>din</span>
                            <span class="caption-savings">Ušteda: <?=$item->savingsDinars?>din (<?=$item->savingsPercentage?>%)</span>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
        <div class="master-footer">
            <a target="_blank" href="https://www.nonstopshop.rs/cms/sale.php">
                <h4 class="master-footer-title">Pogledajte TOP 100 proizvoda na akciji ovde</h4>
            </a>
        </div>
    </div>
<?php endif; ?>

<!-- jQuery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="js/libs/jquery-1.7.min.js">\x3C/script>')</script>
<!-- FlexSlider -->
<script defer src="jquery.flexslider-min.js"></script>
<script type="text/javascript">
    $(window).load(function () {
        $('.flexslider.vertical').flexslider({
            animation: "slide",
            // Krece da radi posle tri sekunde, i na svakom slide-u se zadrzava isto toliko
            slideshowSpeed: 3000,
            // Pauzira se no hover kapiram da je cool fora da kada neko predje  misem da se on zaustavi jer je
            // verovatno zainteresovan za to preko cega je presao misem :)
            pauseOnHover: true,
            controlNav: "thumbnails",
            start: function (slider) {
                $('body').removeClass('loading');
            }
        });
        // horizontal slider 580x200px
        $('.flexslider.horizontal').flexslider({
            animation: "slide",
            controlNav: false,
            slideshowSpeed: 3000,
            animationLoop: true,
            itemWidth: 200,
            itemMargin: 5,
            minItems: 2,
            maxItems: 3
        });
    });
</script>
<!-- Optional FlexSlider Additions -->
<script src="jquery.easing.js"></script>
<script src="jquery.mousewheel.js"></script>
</body>
</html>
