<?php
/**
 * @var \WC_Order $order
 */
$generator = new \Picqer\Barcode\BarcodeGeneratorHTML();

$html = '<html>
<header>
<title>Adresnica-'.$order.'.pdf</title>
<style>
    body, body p, p {
        font-size: 18px;
    }
    .gf-print-bill-wrapper{
        width: 100%;
        padding: 5px;
        margin: auto;
        border: 1px solid;
    }
    .gf-print-bill-number{
        width: 100%;
        padding: 50px;
        padding-bottom:0;
        font-size: 24px;
    }
    .gf-print-bill-info-wrapper{
        margin-left: 50px;
        margin-top: 40px;
    }
    .gf-print-bill__shipping-info{
        text-align: left;
    }
    .gf-print-bill-info-wrapper p{
        margin: 0;
    }
    .gf-print-bill__date-number-method{
        margin-top: 30px;
    }
</style>
</header>
<body>';

$html .= '<div class="gf-print-bill-wrapper">
    <div class="gf-print-bill-number">';

    $dailyExpressFormat = 'SS' . $order->get_date_created()->format('dm')
        . str_replace('201', '', $order->get_date_created()->format('Y'))
        . $order->get_id();
    $html .= $generator->getBarcode($dailyExpressFormat, $generator::TYPE_CODE_128, 2, 50);
    $html .= $dailyExpressFormat;

$html .= '</div>
    <div class="gf-print-bill-info-wrapper">
    <table>
        <tr>    
            <td width="300"><div class="gf-print-bill__customer-info">
            <h4>Pošiljalac:</h4>
            <p>Non Stop Shop d.o.o.</p>
            <p>Žorža Klemansoa 19</p>
            <p>11000 Beograd</p>
            <p>(Stari Grad)</p>
        </div></td>
            <td width="300"><div class="gf-print-bill__shipping-info">
            <h4>Primalac:</h4>';
            if ($order->get_shipping_address_1() !== ''):
                $html .= '<p>'.$order->get_shipping_first_name() .' '. $order->get_shipping_last_name().'</p>
                <p>'.$order->get_shipping_address_1().'</p>
                <p>'.$order->get_shipping_postcode() .', '. $order->get_shipping_city() . ', Srbija</p>';
            else:
                $html .= '<p>'.$order->get_billing_first_name() .' '. $order->get_billing_last_name().'</p>
                <p>'.$order->get_billing_address_1().',</p>
                <p>'.$order->get_billing_postcode() .', '. $order->get_billing_city().'</p>';
            endif;
            $html .= '<p>Int. broj : '.$order->get_order_number().'</p>
            <p>Telefon primaoca : '.$order->get_billing_phone().'</p>
            <p>SMS : </p>
            <p>Vrednost: 0,00</p>';
        if ($order->get_payment_method_title() == 'Pouzećem'):
            $html .= '<p>Otkupnina: '.number_format($order->get_total(), 0).'</p>
            <p>Pošiljalac - Virman</p>';
        else:
            $html .= '<p>Otkupnina: 0,00</p>
            <p>Pošiljalac - Virman</p>';
        endif;
    $html .= '</div></td>
        </tr>
    </table>';

    $html .= '</div>
</div>
</body>
</html>
';