<?php
/**
 * @var \WC_Order $order
 */
?>
<style>
    .gf-print-bill-wrapper{
        width: 60%;
        padding: 5px;
        margin: auto;
        border: 1px solid;
        font-size: 18px;
    }
    .gf-print-bill-number{
        width: 100%;
    }
    .gf-print-bill-header{
        width: 100%;
        text-align: center;
        margin-top: 50px;
        font-weight: bold;
    }
    .gf-print-bill-info-wrapper{
        width: 60%;
        margin-left: 50px;
        margin-top: 40px;
        display: flex;
    }
    .gf-print-bill__customer-info, .gf-print-bill__shipping-info{
        width: 50%;
    }
    .gf-print-bill__shipping-info{
        text-align: left;
    }
    .gf-print-bill-info-wrapper p{
        margin: 0;
    }
    .gf-print-bill__date-number-method{
        margin-top: 30px;
    }
    .gf-print-bill-table{
        width: 75%;
        margin: auto;
        margin-top: 50px;
    }
    .gf-print-bill-table th{
        border-bottom: 1px solid;
    }
    .gf-print-bill-table tfoot{
        border-top: 1px solid;
        font-weight: bolder;
    }
    .gf-print-bill-table__total{
        margin-right: auto;
    }
</style>
<div class="gf-print-bill-wrapper">
    <div class="gf-print-bill-number">

    </div>
    <div class="gf-print-bill-header">

    </div>
    <div class="gf-print-bill-info-wrapper">
        <div class="gf-print-bill__customer-info">
            <h4>Pošiljalac:</h4>
            <p>Non Stop Shop d.o.o.</p>
            <p>Žorža Klemansoa 19</p>
            <p>11000 Beograd</p>
            <p>(Stari Grad)</p>
        </div>
        <div class="gf-print-bill__shipping-info">
            <h4>Primalac:</h4>
            <?php if ($order->get_shipping_address_1() !== ''): ?>
                <p><?=$order->get_shipping_first_name() .' '. $order->get_shipping_last_name()?></p>
                <p><?=$order->get_shipping_address_1()?></p>
                <p><?=$order->get_shipping_postcode() .', '. $order->get_shipping_city() . ', Srbija'?></p>
            <?php else: ?>
                <p><?=$order->get_billing_first_name() .' '. $order->get_billing_last_name()?></p>
                <p><?=$order->get_billing_address_1()?>,</p>
                <p><?=$order->get_billing_postcode() .', '. $order->get_billing_city()?></p>
            <?php endif; ?>
            <p>Int. broj : <?=$order->get_order_number()?></p>
            <p>Telefon primaoca : <?=$order->get_billing_phone()?></p>
        <?php if ($order->get_payment_method_title() == 'Pouzecem'): ?>
            <p>Vrednost: <?=number_format($order->get_total(), 0)?></p>
            <p>Otkupnina: 0,00</p>
            <p>Pošiljalac - Virman</p>
        <?php else: ?>
            <p>Vrednost: 0,00</p>
            <p>Otkupnina: <?=number_format($order->get_total(), 0)?></p>
            <p>Pošiljalac - Virman</p>
        <?php endif; ?>
        </div>
    </div>
</div>